vision_params:
  camera:
    index: 2
    flip: true
  detection:
    margin: 100
    nwindows: 50
    minpix: 150
    track_width_px: 600
  thresholds: 
    binary_threshold: [130,250]
    sobel_threshold: [30,130]
  perspective:
    src_pc: [[0.03, 0.25], [0.97, 0.25], [1, 1], [0, 1.0]]
  node_config:
    rate: 20 #Frequency in Hz
    debug_mode: true