vision_params:
  camera:
    index: 0
  detection:
    margin: 100
    nwindows: 10
    minpix: 150
  thresholds: 
    binary_threshold: [160, 255]
    sobel_threshold: [20, 100]
  perspective:
    src_pc: [[0.15, 0.55], [0.75, 0.55], [1, 1], [0, 1.0]]
